# generic gpio support: platform drivers, dedicated expander chips, etc

obj-$(CONFIG_GPIO_BALONG)	       += gpio_balong.o
obj-$(CONFIG_GPIO_EXPANDER_BALONG) += gpio_expander_balong.o 
obj-$(CONFIG_ENABLE_TEST_CODE)     += gpio_balong_test.o

