KBUILD_CPPFLAGS +=	-Idrivers/modem/om/common \
                    -Idrivers/modem/om/dump \
                    -Idrivers/modem/om/oms\
                    -Idrivers/modem/om/log \
                    -Idrivers/modem/om/sys_view \
		    -Idrivers/modem/om/usbtrace

obj-$(CONFIG_HW_IP_BASE_ADDR)	+= hwadp_balong.o hwadp_memory.o