obj-$(CONFIG_BALONG_MODEM_RESET)        += reset_balong.o
obj-$(CONFIG_BALONG_MODEM_RESET_TEST)   += reset_balong_test.o
obj-$(CONFIG_BALONG_MODEM_POWER_MANAGE) += power_manager_balong.o

obj-$(CONFIG_BALONG_MODEM_RESET)        += load_image.o
EXTRA_CFLAGS += -Idrivers/tzdriver