#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-y		+= temperature_balong.o adp_temperature.o
obj-$(CONFIG_TEMPERATURE_SYS_BALONG)	+= tempsys_device.o
