-include $(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/config/balong_product_config.mk

#头文件
EXTRA_CFLAGS += -Iarch/arm/mach-balong/include/mach 
EXTRA_CFLAGS += -Iarch/arm/mach-balongv7r2/include/mach 
EXTRA_CFLAGS += -Iarch/arm/include/asm 
EXTRA_CFLAGS += -Iinclude/linux 
EXTRA_CFLAGS += -Iinclude/generated 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/product/include/$(OBB_PRODUCT_NAME)/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/product/define/$(OBB_PRODUCT_NAME)/config/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/codec 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/app/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/drv/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/med/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/phy/gphy 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/phy/wphy 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/ps/gups 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/ps/tlps 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/ps/nas 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/taf 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/sdio 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/tools 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/log 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/nvim/include/gu 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/nvim/include/tl/tlps 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/osa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/osa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/scm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/si 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/socp 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/usimm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/errno 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/gu/log 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/gu/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/gu/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/gu/hpa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/lt/msp 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/lt/diag 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/platform/$(CFG_PLATFORM_HISI_BALONG)/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/inc/gu/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/LINK/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/MEMCTRL/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/DICC/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/DIPC/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/MUX/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/FLOWCTRL/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/IMM/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/STL/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/NDIS/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/PPP/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/ND/IPCOMM/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/ND/NDSERVER/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/as/gu/ttf/TTFComm/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/ADS/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/CSD/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/RNIC/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/at/inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/tafapi/inc 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/mcore/TAF/Lib/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/TAFAGENT/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/APPVCOM/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/lt/inc/ccore/gen/
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/nvim/include/lt/tlps  
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/dms 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/cpm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/oam 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/drv 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/gas 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/nas 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/phy 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/tool 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/ttf 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/was   
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/acore/dms 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/ccore/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/ccore/usimm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/si 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/acore/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/hpa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/pstool 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/sc 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/sleep 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/comm/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/comm/bbplog 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/at/inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/tafapi/inc 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/mcore/TAF/Lib/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/TAFAGENT/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/APPVCOM/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/config/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/include_gu/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/product/include/$(CFG_GU_PLATFORM_NEW)/
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/tl/drv/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/tl/oam/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/tl/lps 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/phy/lphy 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/si/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/ccore/om/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/lt/comm/list/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/lt/acore/diag/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/lt/comm/cfg/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/lt/comm/diag/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/lt/comm/drx/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/lt/comm/type/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/acore/om/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/lt/inc/acore/at/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/cpm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/oam 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/drv 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/gas 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/nas 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/phy 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/tool 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/ttf 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/was 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/platform/$(CFG_PLATFORM) 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/platform/$(CFG_PLATFORM)/soc 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/ccore/dh 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/ccore/xml 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/ccore/usimm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/ppm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/hpa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/pstool 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/sc 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/sleep 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/comm/om 

ifneq ($(CFG_RAT_MODE),RAT_GU)
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/lt/msp
endif

ifeq ($(CFG_FEATURE_MERGE_OM_CHAN),FEATURE_ON)
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/acore/cbtcpm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/acore/cbtppm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/ppm
endif

ifeq ($(CFG_FEATURE_BASTET),FEATURE_ON)
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/bastet/inc/
endif

ifeq ($(CFG_FEATURE_MERGE_OM_CHAN),FEATURE_ON)	
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/cpm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/comm/ppm 	
endif


#产品相关的宏定义
EXTRA_CFLAGS += -DVERSION_V3R2 -DVERSION_V3R2_C00 
EXTRA_CFLAGS += -DBOARD_$(CFG_BOARD)
ifeq ($(PRODUCT_CFG_CHIP_BB_TYPE),CHIP_BB_6756CS)
EXTRA_CFLAGS += -D$(PRODUCT_CFG_CHIP_BB_TYPE) \
                -DBOARD_ASIC_BIGPACK
endif

#子系统相关的宏定义
ifneq ($(strip $(CFG_OS_ANDROID_AARCH64)),YES)
EXTRA_CFLAGS += -D__LINUX_ARM_ARCH__=7 -march=armv7-a -Uarm
endif
EXTRA_CFLAGS += -DVOS_LINUX=4 -DOSA_CPU_ACPU=1 -DVOS_OS_VER=VOS_LINUX -DVOS_OSA_CPU=OSA_CPU_ACPU -D__LOG_RELEASE__ \
                -DBSP_CORE_APP -DGU_MODE -DMSP_SUPPORT_USB_VCOM1 -DMSP_SUPPORT_USB_VCOM2 -DVOS_DOPRA_VER=2 -DNDIS_RELEASE \
                -DBALONG_PHY_V200=2 -DBALONG_PHY_V300=3 -DBALONG_PHY_VER=BALONG_PHY_V300 -DBALONG_CHIP_V200=2 \
				-DBALONG_CHIP_V300=3 -DBALONG_CHIP_V500=4 -DBALONG_CHIP_VER=BALONG_CHIP_V500 -DMSP_GUNAS_AT_UNITE -DVERSION_V3R2

#编译器相关的宏定义
EXTRA_CFLAGS += -fsigned-char -DVOS_LINUX=4 -DOSA_CPU_ACPU=1 -DVOS_OS_VER=VOS_LINUX -DVOS_OSA_CPU=OSA_CPU_ACPU -DPRODUCT_CFG_MULTIMODE_LTE -D__LOG_RELEASE__
EXTRA_CFLAGS += -DHAL_DIAG_SDM_USE -Wno-pointer-to-int-cast


#源文件 
taf-objs += comm/src/acore/ADS/Src/AdsCtx.o 
taf-objs += comm/src/acore/ADS/Src/AdsDownLink.o 
taf-objs += comm/src/acore/ADS/Src/AdsInit.o 
taf-objs += comm/src/acore/ADS/Src/AdsTimerMgmt.o 
taf-objs += comm/src/acore/ADS/Src/AdsUpLink.o 
taf-objs += comm/src/acore/ADS/Src/AdsDebug.o 
taf-objs += comm/src/acore/ADS/Src/AdsFilter.o 
taf-objs += comm/src/acore/APPVCOM/Src/AppVcomDev.o 
taf-objs += comm/src/acore/CSD/Src/CsdCtx.o 
taf-objs += comm/src/acore/CSD/Src/CsdDebug.o 
taf-objs += comm/src/acore/CSD/Src/CsdDownLink.o 
taf-objs += comm/src/acore/CSD/Src/CsdUpLink.o 
taf-objs += comm/src/acore/CSD/Src/CsdInit.o 
taf-objs += comm/src/acore/RNIC/Src/RnicCtx.o 
taf-objs += comm/src/acore/RNIC/Src/RnicEntity.o 
taf-objs += comm/src/acore/RNIC/Src/RnicInit.o 
taf-objs += comm/src/acore/RNIC/Src/RnicProcMsg.o 
taf-objs += comm/src/acore/RNIC/Src/RnicTimerMgmt.o 
taf-objs += comm/src/acore/RNIC/Src/RnicDebug.o 
taf-objs += comm/src/acore/RNIC/Src/RnicDemandDialFileIO.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/Taf_MmiStrParse.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/MnMsgDecode.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/MnMsgEncode.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/MnMsgCbEncDec.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/TafApsApi.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/TafMmaApi.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/MnCommApi.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/hi_list.o 
taf-objs += comm/src/mcore/TAF/Lib/Src/TafStdlib.o 

taf-objs += comm/src/acore/TAFAGENT/Src/TafAgent.o 
taf-objs += comm/src/acore/TAFAGENT/Src/TafAgentCtx.o 
taf-objs += comm/src/acore/at/src/AtBasicCmd.o 
taf-objs += comm/src/acore/at/src/AtCheckFunc.o 
taf-objs += comm/src/acore/at/src/AtCmdMsgProc.o 
taf-objs += comm/src/acore/at/src/ATCmdProc.o 
taf-objs += comm/src/acore/at/src/AtCmdSimProc.o 
taf-objs += comm/src/acore/at/src/AtCombinecmd.o 
taf-objs += comm/src/acore/at/src/AtCmdImsProc.o 
taf-objs += comm/src/acore/at/src/AtDataProc.o 
taf-objs += comm/src/acore/at/src/AtDeviceCmd.o 
taf-objs += comm/src/acore/at/src/AtEventReport.o 
taf-objs += comm/src/acore/at/src/AtExtendCmd.o 
taf-objs += comm/src/acore/at/src/AtExtendPrivateCmd.o 
taf-objs += comm/src/acore/at/src/AtInputProc.o 
taf-objs += comm/src/acore/at/src/AtMntn.o 
taf-objs += comm/src/acore/at/src/AtMsgPrint.o 
taf-objs += comm/src/acore/at/src/AtOutputProc.o 
taf-objs += comm/src/acore/at/src/AtParseBasicCmd.o 
taf-objs += comm/src/acore/at/src/AtParseCmd.o 
taf-objs += comm/src/acore/at/src/AtParseCore.o 
taf-objs += comm/src/acore/at/src/AtParseDCmd.o 
taf-objs += comm/src/acore/at/src/AtParseDMCmd.o 
taf-objs += comm/src/acore/at/src/AtParseExtendCmd.o 
taf-objs += comm/src/acore/at/src/AtParsePara.o 
taf-objs += comm/src/acore/at/src/AtParseSCmd.o 
taf-objs += comm/src/acore/at/src/AtQueryParaCmd.o 
taf-objs += comm/src/acore/at/src/AtSetParaCmd.o 
taf-objs += comm/src/acore/at/src/AtTestParaCmd.o 
taf-objs += comm/src/acore/at/src/AtTimer.o 
taf-objs += comm/src/acore/at/src/ATSndMsg.o 
taf-objs += comm/src/acore/at/src/AtAbortParaCmd.o 
taf-objs += comm/src/acore/at/src/AtCtx.o 
taf-objs += comm/src/acore/at/src/AtInit.o 
taf-objs += comm/src/acore/at/src/AtCmdPacketProc.o 
taf-objs += comm/src/acore/at/src/AtCmdFtmProc.o 
taf-objs += comm/src/acore/tafapi/src/MnCallApi.o 
taf-objs += comm/src/acore/tafapi/src/MnMsgApi.o 
taf-objs += comm/src/acore/tafapi/src/Ssa_App_Remote.o 
taf-objs += comm/src/acore/tafapi/src/Taf_Tafm_AppRemote.o 
taf-objs += comm/src/acore/tafapi/src/VcApi.o 
taf-objs += comm/src/acore/dms/src/dms_acm_at_rx.o 
taf-objs += comm/src/acore/dms/src/dms_acm_at_tx.o 
taf-objs += comm/src/acore/dms/src/dms_core.o 
taf-objs += comm/src/acore/dms/src/dms_debug.o 
taf-objs += comm/src/acore/dms/src/dms_ndis.o



taf-objs += lt/src/acore/at/at_lte_common.o
taf-objs += lt/src/acore/at/at_lte_ct_ex_proc.o
taf-objs += lt/src/acore/at/at_lte_ct_ex2_proc.o
taf-objs += lt/src/acore/at/at_lte_ct_proc.o
taf-objs += lt/src/acore/at/at_lte_eventreport.o
taf-objs += lt/src/acore/at/at_lte_ms_proc.o
taf-objs += lt/src/acore/at/at_lte_set_proc.o
taf-objs += lt/src/acore/at/at_lte_st_proc.o
taf-objs += lt/src/acore/at/at_lte_upgrade_proc.o
taf-objs += lt/src/acore/at/AtDeviceCmdTL.o
taf-objs += lt/src/acore/at/at_comm_cmd.o



obj-y  := taf.o



