-include $(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/config/balong_product_config.mk
PSDIR = ..

EXTRA_CFLAGS += -Iarch/arm/mach-balong/include/mach 
EXTRA_CFLAGS += -Iarch/arm/include/asm 
EXTRA_CFLAGS += -Iinclude/linux 
EXTRA_CFLAGS += -Iinclude/generated 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/product/include/$(OBB_PRODUCT_NAME)/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/product/define/$(OBB_PRODUCT_NAME)/config/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/codec 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/app/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/drv/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/med/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/phy/gphy 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/phy/wphy 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/ps/gups 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/ps/tlps 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/ps/nas 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/taf 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/sdio 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/tools 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/log 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/nvim/include/gu 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/nvim/include/tl/tlps 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/osa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/osa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/scm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/si 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/socp 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/usimm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/errno 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/gu/log 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/gu/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/gu/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/gu/hpa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/lt/msp 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/lt/diag 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/platform/$(CFG_PLATFORM_HISI_BALONG)/ 

ifeq ($(CFG_FEATURE_MERGE_OM_CHAN),FEATURE_ON)	
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/cpm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/comm/ppm 	
endif
	
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/inc/gu/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/LINK/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/MEMCTRL/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/DICC/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/DIPC/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/MUX/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/FLOWCTRL/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/IMM/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/STL/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/NDIS/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/PPP/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/ND/IPCOMM/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/comm/comm/ND/NDSERVER/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/ps/as/gu/ttf/TTFComm/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/ADS/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/CSD/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/RNIC/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/at/inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/tafapi/inc 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/mcore/TAF/Lib/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/TAFAGENT/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/APPVCOM/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/lt/inc/ccore/gen/

ifeq ($(CFG_FEATURE_BASTET),FEATURE_ON)
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/bastet/inc/
endif
 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/config/nvim/include/lt/tlps  
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/dms 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/oam/comm/cpm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/oam 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/drv 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/gas 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/nas 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/phy 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/tool 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/ttf 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/include/nv/gu/was   
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/acore/dms 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/ccore/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/ccore/usimm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/si 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/acore/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/hpa 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/nvim 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/pstool 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/sc 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/ccore/sleep 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/comm/om 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/comm/bbplog 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/at/inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/tafapi/inc 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/mcore/TAF/Lib/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/TAFAGENT/Inc/ 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/taf/comm/src/acore/APPVCOM/Inc/ 

ifeq ($(CFG_FEATURE_MERGE_OM_CHAN),FEATURE_ON)
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/acore/cbtcpm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/gu/acore/cbtppm 
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/modem/oam/inc/comm/comm/ppm
endif


#产品相关的宏定义
EXTRA_CFLAGS += -DVERSION_V3R2 -DVERSION_V3R2_C00 

EXTRA_CFLAGS += -DBOARD_$(CFG_BOARD)
ifeq ($(PRODUCT_CFG_CHIP_BB_TYPE),CHIP_BB_6756CS)
EXTRA_CFLAGS += -D$(PRODUCT_CFG_CHIP_BB_TYPE) \
                -DBOARD_ASIC_BIGPACK
endif

#子系统相关的宏定义
ifneq ($(strip $(CFG_OS_ANDROID_AARCH64)),YES)
EXTRA_CFLAGS += -D__LINUX_ARM_ARCH__=7 -march=armv7-a -Uarm
endif

EXTRA_CFLAGS += -DVOS_LINUX=4 -DOSA_CPU_ACPU=1 -DVOS_OS_VER=VOS_LINUX -DVOS_OSA_CPU=OSA_CPU_ACPU -D__LOG_RELEASE__ \
                -DBSP_CORE_APP -DGU_MODE -DMSP_SUPPORT_USB_VCOM1 -DMSP_SUPPORT_USB_VCOM2 -DVOS_DOPRA_VER=2 -DNDIS_RELEASE \
                -DBALONG_PHY_V200=2 -DBALONG_PHY_V300=3 -DBALONG_PHY_VER=BALONG_PHY_V300 -DBALONG_CHIP_V200=2 \
				-DBALONG_CHIP_V300=3 -DBALONG_CHIP_V500=4 -DBALONG_CHIP_VER=BALONG_CHIP_V500 -DMSP_GUNAS_AT_UNITE -DVERSION_V3R2

#编译器相关的宏定义
EXTRA_CFLAGS += -fsigned-char 

gups-objs += $(PSDIR)/comm/comm/DICC/Src/Dicc.o
gups-objs += $(PSDIR)/comm/comm/DIPC/Src/PsDipc.o
gups-objs += $(PSDIR)/comm/comm/MUX/Src/PsMux.o
gups-objs += $(PSDIR)/comm/comm/FLOWCTRL/Src/ACpuLoad.o
gups-objs += $(PSDIR)/comm/comm/FLOWCTRL/Src/Fc.o
gups-objs += $(PSDIR)/comm/comm/FLOWCTRL/Src/FcACore.o
gups-objs += $(PSDIR)/comm/comm/FLOWCTRL/Src/FcACoreCReset.o
gups-objs += $(PSDIR)/comm/comm/IMM/Src/IMMmemMntn.o
gups-objs += $(PSDIR)/comm/comm/IMM/Src/IMMmemRB.o
gups-objs += $(PSDIR)/comm/comm/IMM/Src/IMMmemZC.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_atcmd.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_init.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_input.o
gups-objs += $(PSDIR)/comm/comm/NFEXT/IpsMntn.o
gups-objs += $(PSDIR)/comm/comm/NFEXT/NetfilterEx.o
gups-objs += $(PSDIR)/comm/comm/NFEXT/NetfilterExCtrl.o
gups-objs += $(PSDIR)/comm/comm/HISOCKET/Src/hisocket.o

ifeq ($(CFG_TTF_SKB_EXP), NO)
gups-objs += $(PSDIR)/comm/comm/IMM/Src/IMMmem_PS.o
endif

ifneq ($(strip $(CFG_OS_ANDROID_AARCH64)), YES)
gups-objs += $(PSDIR)/comm/comm/Pstool/Src/Acpu_view.o
endif

ifeq ($(CFG_FEATURE_PPP), FEATURE_ON)
gups-objs += $(PSDIR)/comm/comm/PPP/Src/acf.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/async.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/auth.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/chap.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/hdlc.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ipcp.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/lcp.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/link.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/pap.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_fsm.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_mbuf.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_public.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/pppid.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/proto.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/throughput.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/hdlc_hardware.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/hdlc_software.o
gups-objs += $(PSDIR)/comm/comm/MEMCTRL/Src/TTFMemCtrl.o
endif

obj-y  := gups.o




